##Project Roadmap

0. Setup & Imports
1. Data Understanding
2. Statistical analysis
3. Data Cleaning
4. Univariate Analysis
5. Bivariate Analysis
6. Multivariate Analysis
7. Outlier Analysis (Deep Dive)
8. Key Insights & Conclusion

Step 1 — Check your virtual environment
In your VS Code terminal, paste:
Test-Path .\.venv\Scripts\python.exe


Press Enter.
- If you see True, continue to Step 2.
- If you see False, run this command to create the environment:
& "C:\Users\hp\.local\bin\python3.14.exe" -m venv .venv


Step 2 — Install the required libraries
Paste this single command in your terminal:
.\.venv\Scripts\python.exe -m pip install ipykernel pandas numpy matplotlib seaborn scipy scikit-learn


Press Enter and wait for installation to complete.
If the error says No module named pip, run:
.\.venv\Scripts\python.exe -m ensurepip --upgrade


Then repeat the installation command above.
Step 3 — Select the correct Python kernel
In your VS Code notebook:
1. Click Select Kernel at the top-right.
2. Click Python Environments.
3. Select the Python interpreter inside your project's .venv folder.
4. If it isn't listed, use Select Interpreter Path and locate .venv\Scripts\python.exe.
This is important because your screenshot shows VS Code is still trying to run the other Python 3.14.6 installation.

## 0. Setup & Imports

In [1]:
import numpy as np

import pandas as pd

import matplotlib.pyplot as plt

import seaborn as sns

from scipy import stats

import warnings
warnings.filterwarnings("ignore")

%matplotlib inline

print("All libraries are working!")

All libraries are working!

In [7]:
df=pd.read_csv("fetal_health.csv")

df.head()

,baseline value,accelerations,fetal_movement,uterine_contractions,light_decelerations,severe_decelerations,prolongued_decelerations,abnormal_short_term_variability,mean_value_of_short_term_variability,percentage_of_time_with_abnormal_long_term_variability,...,histogram_min,histogram_max,histogram_number_of_peaks,histogram_number_of_zeroes,histogram_mode,histogram_mean,histogram_median,histogram_variance,histogram_tendency,fetal_health
0,120.0,0.000,0.0,0.000,0.000,0.0,0.0,73.0,0.5,43.0,...,62.0,126.0,2.0,0.0,120.0,137.0,121.0,73.0,1.0,2.0
1,132.0,0.006,0.0,0.006,0.003,0.0,0.0,17.0,2.1,0.0,...,68.0,198.0,6.0,1.0,141.0,136.0,140.0,12.0,0.0,1.0
2,133.0,0.003,0.0,0.008,0.003,0.0,0.0,16.0,2.1,0.0,...,68.0,198.0,5.0,1.0,141.0,135.0,138.0,13.0,0.0,1.0
3,134.0,0.003,0.0,0.008,0.003,0.0,0.0,16.0,2.4,0.0,...,53.0,170.0,11.0,0.0,137.0,134.0,137.0,13.0,1.0,1.0
4,132.0,0.007,0.0,0.008,0.000,0.0,0.0,16.0,2.4,0.0,...,53.0,170.0,9.0,0.0,137.0,136.0,138.0,11.0,1.0,1.0

In [16]:
df.head(1)

,baseline value,accelerations,fetal_movement,uterine_contractions,light_decelerations,severe_decelerations,prolongued_decelerations,abnormal_short_term_variability,mean_value_of_short_term_variability,percentage_of_time_with_abnormal_long_term_variability,...,histogram_min,histogram_max,histogram_number_of_peaks,histogram_number_of_zeroes,histogram_mode,histogram_mean,histogram_median,histogram_variance,histogram_tendency,fetal_health
0,120.0,0.0,0.0,0.0,0.0,0.0,0.0,73.0,0.5,43.0,...,62.0,126.0,2.0,0.0,120.0,137.0,121.0,73.0,1.0,2.0

In [8]:
df.tail()

,baseline value,accelerations,fetal_movement,uterine_contractions,light_decelerations,severe_decelerations,prolongued_decelerations,abnormal_short_term_variability,mean_value_of_short_term_variability,percentage_of_time_with_abnormal_long_term_variability,...,histogram_min,histogram_max,histogram_number_of_peaks,histogram_number_of_zeroes,histogram_mode,histogram_mean,histogram_median,histogram_variance,histogram_tendency,fetal_health
2121,140.0,0.000,0.000,0.007,0.0,0.0,0.0,79.0,0.2,25.0,...,137.0,177.0,4.0,0.0,153.0,150.0,152.0,2.0,0.0,2.0
2122,140.0,0.001,0.000,0.007,0.0,0.0,0.0,78.0,0.4,22.0,...,103.0,169.0,6.0,0.0,152.0,148.0,151.0,3.0,1.0,2.0
2123,140.0,0.001,0.000,0.007,0.0,0.0,0.0,79.0,0.4,20.0,...,103.0,170.0,5.0,0.0,153.0,148.0,152.0,4.0,1.0,2.0
2124,140.0,0.001,0.000,0.006,0.0,0.0,0.0,78.0,0.4,27.0,...,103.0,169.0,6.0,0.0,152.0,147.0,151.0,4.0,1.0,2.0
2125,142.0,0.002,0.002,0.008,0.0,0.0,0.0,74.0,0.4,36.0,...,117.0,159.0,2.0,1.0,145.0,143.0,145.0,1.0,0.0,1.0

In [10]:
df.shape

(2126, 22)

In [15]:
print(f"Shape: {df.shape[0]} rows x {df.shape[1]} columns")

Shape: 2126 rows x 22 columns

## 1. Data Understanding

1.1 Structure & Data Types

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2126 entries, 0 to 2125
Data columns (total 22 columns):
 #   Column                                                  Non-Null Count  Dtype
---  ------                                                  --------------  -----
 0   baseline value                                          2126 non-null   float64
 1   accelerations                                           2126 non-null   float64
 2   fetal_movement                                          2126 non-null   float64
 3   uterine_contractions                                    2126 non-null   float64
 4   light_decelerations                                     2126 non-null   float64
 5   severe_decelerations                                    2126 non-null   float64
 6   prolongued_decelerations                                2126 non-null   float64
 7   abnormal_short_term_variability                         2126 non-null   float64
 8   mean_value_of_short_term_variability                    2126 non-null   float64
 9   percentage_of_time_with_abnormal_long_term_variability  2126 non-null   float64
 10  mean_value_of_long_term_variability                     2126 non-null   float64
 11  histogram_width                                         2126 non-null   float64
 12  histogram_min                                           2126 non-null   float64
 13  histogram_max                                           2126 non-null   float64
 14  histogram_number_of_peaks                               2126 non-null   float64
 15  histogram_number_of_zeroes                              2126 non-null   float64
 16  histogram_mode                                          2126 non-null   float64
 17  histogram_mean                                          2126 non-null   float64
 18  histogram_median                                        2126 non-null   float64
 19  histogram_variance                                      2126 non-null   float64
 20  histogram_tendency                                      2126 non-null   float64
 21  fetal_health                                            2126 non-null   float64
dtypes: float64(22)
memory usage: 365.5 KB

In [22]:
df.columns.tolist()
df.describe().T

,count,mean,std,min,25%,50%,75%,max
baseline value,2126.0,133.303857,9.840844,106.0,126.000,133.000,140.000,160.000
accelerations,2126.0,0.003178,0.003866,0.0,0.000,0.002,0.006,0.019
fetal_movement,2126.0,0.009481,0.046666,0.0,0.000,0.000,0.003,0.481
uterine_contractions,2126.0,0.004366,0.002946,0.0,0.002,0.004,0.007,0.015
light_decelerations,2126.0,0.001889,0.002960,0.0,0.000,0.000,0.003,0.015
severe_decelerations,2126.0,0.000003,0.000057,0.0,0.000,0.000,0.000,0.001
prolongued_decelerations,2126.0,0.000159,0.000590,0.0,0.000,0.000,0.000,0.005
abnormal_short_term_variability,2126.0,46.990122,17.192814,12.0,32.000,49.000,61.000,87.000
mean_value_of_short_term_variability,2126.0,1.332785,0.883241,0.2,0.700,1.200,1.700,7.000
percentage_of_time_with_abnormal_long_term_variability,2126.0,9.846660,18.396880,0.0,0.000,0.000,11.000,91.000
mean_value_of_long_term_variability,2126.0,8.187629,5.628247,0.0,4.600,7.400,10.800,50.700
histogram_width,2126.0,70.445908,38.955693,3.0,37.000,67.500,100.000,180.000
histogram_min,2126.0,93.579492,29.560212,50.0,67.000,93.000,120.000,159.000
histogram_max,2126.0,164.025400,17.944183,122.0,152.000,162.000,174.000,238.000
histogram_number_of_peaks,2126.0,4.068203,2.949386,0.0,2.000,3.000,6.000,18.000
histogram_number_of_zeroes,2126.0,0.323612,0.706059,0.0,0.000,0.000,0.000,10.000
histogram_mode,2126.0,137.452023,16.381289,60.0,129.000,139.000,148.000,187.000
histogram_mean,2126.0,134.610536,15.593596,73.0,125.000,136.000,145.000,182.000
histogram_median,2126.0,138.090310,14.466589,77.0,129.000,139.000,148.000,186.000
histogram_variance,2126.0,18.808090,28.977636,0.0,2.000,7.000,24.000,269.000
histogram_tendency,2126.0,0.320320,0.610829,-1.0,0.000,0.000,1.000,1.000
fetal_health,2126.0,1.304327,0.614377,1.0,1.000,1.000,1.000,3.000